"""Structural protocol for workflow functions (avoids importing auditor.graph)."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from auditor.config import Settings
from auditor.evidence_store import EvidenceStore
from auditor.state import AuditorState, Finding


@runtime_checkable
class AuditRuntime(Protocol):
    """Attributes and helpers workflow nodes may use on the orchestration façade.

    Implemented by :class:`~auditor.graph.AuditorGraph`. Workflow code types
    against this protocol so modules never import ``auditor.graph``.
    """

    settings: Settings
    tools: list[Any]
    tools_by_name: dict[str, Any]
    evidence_model: Any
    evidence_model_ssh: Any
    fill_model: Any
    playbooks: Any | None
    _evidence_by_run: dict[str, EvidenceStore]
    _multi_sessions: dict[str, dict[str, Any]]
    _orphan_tasks: dict[str, Any]
    _checkpointer: Any
    _checkpoint_conn: Any | None
    _checkpoint_scope_key: str
    _async_cp_ready: bool
    _sqlite_cm: Any | None
    graph: Any
    intake_graph: Any

    async def ensure_async_checkpointer(self, *args: Any, **kwargs: Any) -> None: ...

    def _build(self, *args: Any, **kwargs: Any) -> Any: ...

    def _build_intake(self, *args: Any, **kwargs: Any) -> Any: ...

    def _evidence_llm(self) -> Any: ...

    def _store_from_state(self, state: AuditorState) -> EvidenceStore | None: ...

    async def _fill_requirement_cells(self, *args: Any, **kwargs: Any) -> Finding: ...

    async def _gather_evidence(self, *args: Any, **kwargs: Any) -> str: ...

    async def _execute_tool_calls(self, *args: Any, **kwargs: Any) -> list[Any]: ...

    def _cells_to_finding(self, *args: Any, **kwargs: Any) -> Finding: ...

    def _deterministic_it_audit_finding(self, *args: Any, **kwargs: Any) -> Finding | None: ...

    def _skipped_finding(self, *args: Any, **kwargs: Any) -> Finding: ...

    async def _warehouse_live_upsert(self, *args: Any, **kwargs: Any) -> None: ...

    def _results_session_number(self, *args: Any, **kwargs: Any) -> int | None: ...

    def _report_language(self, *args: Any, **kwargs: Any) -> Any: ...

    def _report_language_from_request(self, user_request: str) -> Any: ...

    def _persist_intake_progress(self, *args: Any, **kwargs: Any) -> None: ...

    def _load_intake_progress(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...

    async def _intake_llm_json(self, *args: Any, **kwargs: Any) -> dict[str, Any] | None: ...

    async def _intake_resolve_yes_no(self, *args: Any, **kwargs: Any) -> Any: ...

    async def _intake_resolve_client_name(self, *args: Any, **kwargs: Any) -> Any: ...

    async def _intake_resolve_audit_type(self, *args: Any, **kwargs: Any) -> Any: ...

    async def _collect_host_facts(self, *args: Any, **kwargs: Any) -> Any: ...

    async def _collect_host_facts_llm(self, *args: Any, **kwargs: Any) -> Any: ...

    async def _collect_host_facts_compact(self, *args: Any, **kwargs: Any) -> Any: ...

    async def _discover_inventory_hosts(self, *args: Any, **kwargs: Any) -> Any: ...

    async def _llm_route_frameworks_from_software(self, *args: Any, **kwargs: Any) -> Any: ...

    def _jobs_from_selected_intake(self, *args: Any, **kwargs: Any) -> Any: ...

    def _format_host_framework_plan(self, *args: Any, **kwargs: Any) -> str: ...

    def _remember_multi_session(self, thread_id: str, session: dict[str, Any]) -> None: ...

    def _forget_multi_session(self, thread_id: str) -> dict[str, Any] | None: ...

    def _reload_multi_sessions(self, run_id: str) -> None: ...

    def _decorate_result(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...

    def _target_scope(self, *args: Any, **kwargs: Any) -> Any: ...

    def _client_slug_from_values(self, values: dict[str, Any] | None) -> str | None: ...

    async def arun_one(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...

    async def arun_intake(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...

    async def aresume(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...

    async def route_framework_node(self, *args: Any, **kwargs: Any) -> Any: ...

    async def load_framework(self, *args: Any, **kwargs: Any) -> Any: ...

    async def collect_host_facts(self, *args: Any, **kwargs: Any) -> Any: ...

    async def assess_parallel(self, *args: Any, **kwargs: Any) -> Any: ...

    async def reconnect_session(self, *args: Any, **kwargs: Any) -> Any: ...

    async def human_gate(self, *args: Any, **kwargs: Any) -> Any: ...

    async def finalize(self, *args: Any, **kwargs: Any) -> Any: ...

    async def intake_gate(self, *args: Any, **kwargs: Any) -> Any: ...

    async def _facts_from_host_facts_evidence(self, *args: Any, **kwargs: Any) -> Any: ...

    def _multi_progress_preamble(self, *args: Any, **kwargs: Any) -> str: ...

    async def _schedule_framework_jobs(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...

    async def _run_framework_jobs(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...

    async def _merge_multi_reports(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...

    async def _continue_multi_after_resume(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...

    async def _start_frameworks_after_intake(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...

    def route_after_assess(self, state: AuditorState) -> str: ...

    def route_after_hitl(self, state: AuditorState) -> str: ...
