"""Domain package for audit execution entities."""

from __future__ import annotations

from auditor.domain.audit_models import (
    AUDIT_JOB_TRANSITIONS,
    AUDIT_RUN_TRANSITIONS,
    AuditJob,
    AuditJobStatus,
    AuditJobType,
    AuditRun,
    AuditRunStatus,
    InvalidStatusTransition,
    JobErrorInfo,
    can_complete_run,
    latest_jobs_by_task,
    new_audit_run_id,
    new_job_id,
    resolve_terminal_run_status,
    validate_job_transition,
    validate_run_transition,
)
from auditor.domain.result_identity import (
    DuplicateLogicalKeyError,
    DuplicateResultIdError,
    IncompleteResultIdentityError,
    ResultLogicalKey,
    finding_for_requirement,
    index_by_result_id,
    logical_key_of,
    merge_result_maps,
    new_result_id,
    requirement_ids_in,
    result_id_of,
    validate_result_identity,
)

__all__ = [
    "AUDIT_JOB_TRANSITIONS",
    "AUDIT_RUN_TRANSITIONS",
    "AuditJob",
    "AuditJobStatus",
    "AuditJobType",
    "AuditRun",
    "AuditRunStatus",
    "DuplicateLogicalKeyError",
    "DuplicateResultIdError",
    "IncompleteResultIdentityError",
    "InvalidStatusTransition",
    "JobErrorInfo",
    "ResultLogicalKey",
    "can_complete_run",
    "finding_for_requirement",
    "index_by_result_id",
    "latest_jobs_by_task",
    "logical_key_of",
    "merge_result_maps",
    "new_audit_run_id",
    "new_job_id",
    "new_result_id",
    "requirement_ids_in",
    "resolve_terminal_run_status",
    "result_id_of",
    "validate_job_transition",
    "validate_result_identity",
    "validate_run_transition",
]
